export const courseSource = {
  label: "Namaste DSA public course outline",
  url: "https://namastedev.com/learn/namaste-dsa",
};

export const courseModules = [
  {
    id: "introduction",
    title: "1 Introduction",
    items: [
      { id: 13, title: "Introduction" },
      { id: 14, title: "Which language?" },
    ],
  },
  {
    id: "warm-up",
    title: "2 Warm Up",
    items: [
      { id: 15, title: "Warm Up - Introduction" },
      { id: 16, title: "Programming 101" },
      { id: 17, title: "Function, if-else" },
      { id: 18, title: "Loops 01" },
      { id: 19, title: "Loops 02" },
      { id: 20, title: "Second Largest" },
      { id: 21, title: "Loop in Loop" },
      { id: 22, title: "Star Pattern" },
      { id: 23, title: "Count Digit" },
      { id: 24, title: "Palindrome" },
      { id: 25, title: "Reverse Integer" },
    ],
  },
  {
    id: "complexity",
    title: "3 Time/Space Complexity",
    items: [{ id: 26, title: "Time & Space Complexity" }],
  },
  {
    id: "arrays",
    title: "4 Arrays - Easy/Medium",
    items: [
      { id: 27, title: "Remove Duplicates" },
      { id: 28, title: "Remove Element" },
      { id: 29, title: "Reverse String" },
      { id: 30, title: "Best Time to Buy and Sell Stocks" },
      { id: 31, title: "Merge Sorted Arrays" },
      { id: 32, title: "Move Zeros" },
      { id: 33, title: "Max Consecutive Ones" },
      { id: 34, title: "Missing Number" },
      { id: 35, title: "Single Number" },
    ],
  },
  {
    id: "recursion",
    title: "5 Recursion - Easy/Medium",
    items: [
      { id: 36, title: "Recursion 101" },
      { id: 37, title: "Sum of first n numbers" },
      { id: 38, title: "Sum of all numbers in Array" },
      { id: 39, title: "Factorial of n" },
      { id: 40, title: "Power of Two" },
      { id: 41, title: "Recursion Masterclass" },
    ],
  },
  {
    id: "searching-sorting",
    title: "6 Searching & Sorting - Easy/Medium",
    items: [
      { id: 42, title: "Linear Search" },
      { id: 43, title: "Binary Search" },
      { id: 44, title: "Bubble Sort" },
      { id: 45, title: "Selection Sort" },
      { id: 46, title: "Insertion Sort" },
      { id: 47, title: "Merge Sort" },
    ],
  },
  {
    id: "linked-list",
    title: "7 Linked List - Easy/Medium",
    items: [
      { id: 48, title: "Introduction to Linked List" },
      { id: 49, title: "Design Linked List" },
      { id: 50, title: "Adding Nodes to Linked List" },
      { id: 51, title: "Deleting Nodes in Linked List" },
      { id: 52, title: "Middle of Linked List" },
      { id: 53, title: "Reverse Linked List" },
      { id: 54, title: "Linked List Cycle - Hash Table" },
      { id: 55, title: "Linked List Cycle - Floyd's Algorithm" },
      { id: 56, title: "Palindrome Linked List" },
      { id: 57, title: "Intersection of two Linked Lists" },
      { id: 58, title: "Remove Linked List Elements" },
      { id: 59, title: "Remove nth node from end of List - Two Pass" },
      { id: 60, title: "Remove nth Node from end - One Pass" },
      { id: 61, title: "Remove Duplicates from Sorted List" },
      { id: 62, title: "Odd Even Linked List" },
      { id: 63, title: "Add Two Numbers" },
      { id: 64, title: "Merge Two Sorted Lists" },
      { id: 65, title: "Rotate List" },
      { id: 66, title: "Swap Nodes in Pairs - Iterative Approach" },
      { id: 67, title: "Swap Nodes in Pair - Recursive Approach" },
    ],
  },
  {
    id: "strings",
    title: "8 Strings - Easy/Medium",
    items: [
      { id: 68, title: "Length of Last Word - Approach 1 - Two Loops" },
      { id: 69, title: "Length of Last Word - Approach 2 - One Loop" },
      { id: 70, title: "Find Words Containing Character" },
      { id: 71, title: "Jewels and Stones" },
      { id: 72, title: "Find Most Frequent Vowel and Consonant" },
      { id: 73, title: "Split a String in Balanced Strings" },
      { id: 74, title: "Reverse String II" },
      { id: 75, title: "Valid Palindrome - Approach 1 - Extra Space" },
      { id: 76, title: "Valid Palindrome - Approach 2 - Two Pointers" },
      { id: 77, title: "Largest Odd Number in a String" },
      { id: 78, title: "Longest Common Prefix" },
      { id: 79, title: "Valid Anagram" },
      { id: 80, title: "Isomorphic Strings" },
      { id: 81, title: "Group Anagrams - Approach 1 - Sorted Key" },
      { id: 82, title: "Group Anagrams - Approach 2 - Hashed Key" },
    ],
  },
  {
    id: "stack-queue",
    title: "9 Stack and Queues",
    items: [
      { id: 83, title: "Introduction to Stacks & Queues" },
      { id: 84, title: "Playing with Stacks & Queues" },
      { id: 85, title: "Implement Stack using Two Queues" },
      { id: 86, title: "Implement Stack using One Queue" },
      { id: 87, title: "Implement Queue using Stacks" },
      { id: 88, title: "Valid Parentheses" },
      { id: 89, title: "Min Stack" },
      { id: 90, title: "Remove Outermost Parentheses - Using Stack" },
      { id: 91, title: "Remove Outermost Parentheses - without Stack" },
      { id: 92, title: "Evaluate Reverse Polish Notation" },
      { id: 93, title: "Next Greater Element" },
      { id: 94, title: "Daily Temperatures" },
      { id: 95, title: "Next Greater Element - II" },
      { id: 96, title: "Rotting Oranges" },
    ],
  },
  {
    id: "binary-search",
    title: "10 Binary Search Algorithm",
    items: [
      { id: 97, title: "Square Root of X" },
      { id: 98, title: "Best Practice - Finding Middle Element" },
      { id: 99, title: "Guess Higher or Lower" },
      { id: 100, title: "Search in Rotated Sorted Array" },
      { id: 101, title: "First Bad Version" },
      { id: 102, title: "Find Peak Element" },
      { id: 103, title: "Find Minimum in Rotated Sorted Array" },
      { id: 104, title: "Find First & Last Position in Sorted Array" },
      { id: 105, title: "Find First & Last Position in Sorted Array - Approach 2" },
      { id: 106, title: "Find Peak in a Mountain Array" },
      { id: 107, title: "Single Element in a Sorted Array" },
      { id: 108, title: "Find k Closest Elements" },
    ],
  },
  {
    id: "two-pointers-sliding-window",
    title: "11 Two Pointers & Sliding Window",
    items: [
      { id: 109, title: "Two Sum" },
      { id: 110, title: "Two Sum II - Input Array Is Sorted" },
      { id: 111, title: "Is Subsequence" },
      { id: 112, title: "Find Index of First Occurrence in String" },
      { id: 113, title: "KMP (Knuth-Morris-Pratt) Algorithm" },
      { id: 114, title: "Intersection of Two Linked Lists - Two Pointers" },
      { id: 115, title: "Container with Most Water" },
      { id: 116, title: "Three Sum" },
      { id: 117, title: "Trapping Rain Water" },
      { id: 118, title: "Longest Substring Without Repeating Characters" },
      { id: 119, title: "Longest Repeating Character Replacement" },
      { id: 120, title: "Permutation in String" },
      { id: 121, title: "Sliding Window Maximum" },
    ],
  },
  {
    id: "binary-tree",
    title: "12 Binary Tree",
    items: [
      { id: 122, title: "Introduction to Trees" },
      { id: 123, title: "Binary Tree - Traversals Explained" },
      { id: 124, title: "Preorder Traversal - Recursive Approach" },
      { id: 125, title: "Inorder & PostOrder - Recursive Approach" },
      { id: 126, title: "Preorder Traversal - Iterative Approach" },
      { id: 127, title: "Inorder Traversal - Iterative Approach" },
      { id: 128, title: "Postorder - Iterative Approach - 2 Stacks" },
      { id: 129, title: "Postorder - Iterative Approach - One Stack" },
      { id: 130, title: "DFS and BFS in Binary Tree" },
      { id: 131, title: "Level Order Traversal - Queue - BFS" },
      { id: 132, title: "Level Order Traversal - Recursive Approach" },
      { id: 133, title: "Maximum Depth of Binary Tree" },
      { id: 134, title: "Path Sum" },
      { id: 135, title: "Symmetric Tree - Recursive Approach" },
      { id: 136, title: "Symmetric Tree - Iterative Approach" },
      { id: 137, title: "Invert a Binary Tree" },
      { id: 138, title: "Same Tree" },
      { id: 139, title: "Balanced Binary Tree" },
      { id: 140, title: "Diameter of a Binary Tree" },
      { id: 141, title: "Zigzag Level Order Traversal" },
      { id: 142, title: "Subtree of another Tree" },
      { id: 143, title: "Lowest Common Ancestor" },
      { id: 144, title: "Binary Tree Right Side View" },
      { id: 145, title: "Count Good Nodes in Binary Tree" },
      { id: 146, title: "Populating Next Right Pointers in Each Node" },
      { id: 147, title: "Binary Tree Maximum Path Sum" },
    ],
  },
  {
    id: "bst",
    title: "13 Binary Search Tree",
    items: [
      { id: 148, title: "Binary Search Tree - Introduction" },
      { id: 149, title: "Valid Binary Search Tree" },
      { id: 150, title: "Search in a BST" },
      { id: 151, title: "Insert into a BST" },
      { id: 152, title: "Kth Smallest Element" },
      { id: 153, title: "Lowest Common Ancestor of a BST" },
    ],
  },
  {
    id: "heap-priority-queue",
    title: "14 Heap / Priority Queue",
    items: [
      { id: 154, title: "Introduction to Heaps" },
      { id: 155, title: "Creating a Heap" },
      { id: 156, title: "Inserting a node in Heap" },
      { id: 157, title: "Extracting Values in Heap & HeapifyDown" },
      { id: 158, title: "Heap Sort Algorithm" },
      { id: 159, title: "Heap Sort Code" },
      { id: 160, title: "Heap Sort - Dive Deep" },
      { id: 161, title: "Priority Queues - Introduction" },
      { id: 162, title: "Priority Queue Code" },
      { id: 163, title: "Kth Largest Element in an Array" },
      { id: 164, title: "Kth Largest Element in a Stream" },
      { id: 165, title: "Last Stone Weight" },
      { id: 166, title: "Top K Frequent Elements" },
      { id: 167, title: "Kth Smallest Element in a Sorted Matrix" },
    ],
  },
  {
    id: "hashing",
    title: "15 Hashing",
    items: [
      { id: 54, title: "Linked List Cycle - Hash Table" },
      { id: 56, title: "Palindrome Linked List" },
      { id: 114, title: "Intersection of Two Linked Lists - Two Pointers" },
      { id: 61, title: "Remove Duplicates from Sorted List" },
      { id: 70, title: "Find Words Containing Character" },
      { id: 71, title: "Jewels and Stones" },
      { id: 72, title: "Find Most Frequent Vowel and Consonant" },
      { id: 75, title: "Valid Palindrome - Approach 1 - Extra Space" },
      { id: 79, title: "Valid Anagram" },
      { id: 80, title: "Isomorphic Strings" },
      { id: 81, title: "Group Anagrams - Approach 1 - Sorted Key" },
      { id: 82, title: "Group Anagrams - Approach 2 - Hashed Key" },
      { id: 93, title: "Next Greater Element" },
      { id: 110, title: "Two Sum II - Input Array Is Sorted" },
      { id: 112, title: "Find Index of First Occurrence in String" },
      { id: 113, title: "KMP (Knuth-Morris-Pratt) Algorithm" },
      { id: 120, title: "Permutation in String" },
      { id: 118, title: "Longest Substring Without Repeating Characters" },
      { id: 121, title: "Sliding Window Maximum" },
    ],
  },
  {
    id: "backtracking",
    title: "16 Backtracking",
    items: [
      { id: 168, title: "Introduction to Backtracking" },
      { id: 169, title: "Subsets - The Power Set" },
      { id: 170, title: "Combinations" },
      { id: 171, title: "Permutations" },
      { id: 172, title: "Subset - II" },
      { id: 173, title: "Combination Sum" },
      { id: 174, title: "Combination Sum - II" },
      { id: 175, title: "Combination Sum - III" },
      { id: 176, title: "Letter Combinations of a Phone Number" },
      { id: 177, title: "Permutations - II" },
      { id: 178, title: "Palindrome Partitioning" },
      { id: 179, title: "Word Search" },
      { id: 180, title: "N Queens" },
    ],
  },
  {
    id: "greedy",
    title: "17 Greedy Algorithm",
    items: [
      { id: 181, title: "Introduction to Greedy Algorithm" },
      { id: 182, title: "Two City Scheduling" },
      { id: 183, title: "Assign Cookies" },
      { id: 184, title: "Lemonade Change" },
      { id: 185, title: "Best Time to Buy and Sell Stock - II" },
      { id: 186, title: "Insert Interval" },
      { id: 187, title: "Merge Intervals" },
      { id: 188, title: "Partition Labels" },
      { id: 189, title: "Non Overlapping Intervals" },
      { id: 190, title: "Task Scheduler" },
      { id: 191, title: "Gas Station" },
      { id: 192, title: "Car Pooling" },
      { id: 193, title: "Candy - Two Pass - O(n) Space" },
      { id: 194, title: "Candy - One Pass - O(1) Space" },
    ],
  },
  {
    id: "dynamic-programming",
    title: "18 Dynamic Programming",
    items: [
      { id: 195, title: "Introduction to Dynamic Programming" },
      { id: 196, title: "Fibonacci Numbers using DP" },
      { id: 197, title: "Top Down & Bottom Up - DP approach" },
      { id: 198, title: "Climbing Stairs" },
      { id: 199, title: "Minimum Cost Climbing Stairs" },
      { id: 200, title: "House Robber" },
      { id: 201, title: "House Robber II" },
      { id: 202, title: "Coin Change - Top Down - Recursive" },
      { id: 203, title: "Coin Change - Bottom Up - Iterative" },
      { id: 204, title: "Palindromic Substrings" },
      { id: 205, title: "Longest Palindromic Substring" },
      { id: 206, title: "Decode Ways" },
      { id: 207, title: "Maximum Subarray - Kadane's Algorithm" },
      { id: 208, title: "Maximum Product Subarray - Approach 1" },
      { id: 209, title: "Maximum Product Subarray - Approach 2" },
      { id: 210, title: "Word Break" },
      { id: 211, title: "Longest Increasing Subsequence" },
      { id: 212, title: "Partition Equal Subset Sum" },
      { id: 213, title: "Coin Change II" },
      { id: 214, title: "Unique Paths" },
    ],
  },
  {
    id: "graphs",
    title: "19 Graphs",
    items: [
      { id: 215, title: "Introduction to Graphs" },
      { id: 216, title: "Breadth First Search (BFS)" },
      { id: 217, title: "Depth First Search (DFS)" },
      { id: 218, title: "Find if Path Exists - BFS" },
      { id: 219, title: "DFS Recursive" },
      { id: 220, title: "All Paths from Source to Target" },
      { id: 221, title: "Reconstruct Itinerary" },
      { id: 222, title: "Detect Cycle in Undirected Connected Graph" },
      { id: 223, title: "Topological Sort - DFS Preview" },
      { id: 224, title: "Kahn's Algorithm - Topological Sort - BFS Preview" },
      { id: 225, title: "Shortest Path Algorithms in Graphs" },
      { id: 226, title: "Shortest Path in Unweighted Graph - BFS" },
      { id: 227, title: "Dijkstra's Algorithm - Shortest Path Weighted Graph" },
      { id: 228, title: "Dijkstra's Algorithm - Code" },
      { id: 229, title: "Bellman Ford Algorithm - Shortest Path with Negative Weights" },
      { id: 230, title: "Bellman Ford Algorithm - Code" },
      { id: 231, title: "Floyd Warshall Algorithm - All Pairs Shortest Path" },
      { id: 232, title: "Floyd Warshall - Code" },
      { id: 233, title: "Comparing all Shortest Path Graph Algorithms" },
      { id: 234, title: "Minimum Spanning Tree" },
      { id: 235, title: "Prim's Algorithm" },
      { id: 236, title: "Prim's Algorithm - Code" },
      { id: 237, title: "Disjoint Set - Union Find" },
      { id: 238, title: "Kruskal's Algorithm" },
      { id: 239, title: "Kruskal + Union Find - Code" },
      { id: 240, title: "Comparison - Prim’s vs Kruskal Algorithm" },
      { id: 241, title: "Number of Operations to Make Network Connected" },
      { id: 242, title: "Cheapest Flight with K Stops" },
      { id: 243, title: "Number of Ways to Arrive at Destination" },
      { id: 244, title: "Min Cost to Connect All Points" },
    ],
  },
  {
    id: "tries",
    title: "20 Tries",
    items: [
      { id: 245, title: "Introduction to Tries" },
      { id: 246, title: "Trie and TrieNode Structure" },
      { id: 247, title: "Insert, Search, PrefixFind - Trie Code" },
      { id: 248, title: "Time & Space Complexity in Tries" },
    ],
  },
];
